//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Auto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automovil
    {
        public int Id_auto { get; set; }
        public int id_modelo { get; set; }
        public int id_vendedor { get; set; }
        public int km { get; set; }
        public string tipo_combustible { get; set; }
        public decimal precio { get; set; }
        public int anio { get; set; }
    
        public virtual Modelo Modelo { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
