//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Auto.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public Vendedor()
        {
            this.Automovil = new HashSet<Automovil>();
        }
    
        public int id_vendedor { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string e_mail { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<Automovil> Automovil { get; set; }
    }
}
